### ISSUE TITLE
STDERR output lost during shutdown

### ISSUE THREAD

**Issue by EricByers** [bugsnag/panicwrap#10] opened 2018-11-28 14:26 UTC
### Expected behavior
STDERR continues to output after SIGTERM is triggered

### Observed behavior
Messages to STDERR are not sent after SIGTERM/shutdown starts

### Steps to reproduce
* Add handler for SIGTERM
* Log to STDERR in handler

### Version
1.2.0

### Additional information
Using as part of bugsnag-go, added bugsnag handler and lost all our STDERR output during SIGTERM handling/shutdown.

It appears to be related to monitor.go's Pipe, which appears to get closed too soon (https://github.com/bugsnag/panicwrap/blob/master/monitor.go#L38)

**Comment by takkyuuplayer** [comment] 2021-01-13 15:24
It happens with SIGINT signal, too.

### Steps to reproduce

1. Run below code snippet `go run main.go`
2. send SIGINT signal by Ctrl+C 

Expected: It outputs `Worker shutting down` and `Worker shut down`.
Actual: It won't output those messages.

### Environment

* Bugsnag version: v1.9.0
* Go version: 1.15.6 darwin/amd64
* Integration framework version: None

### Example code snippet

```
// main.go
package main

import (
	"log"
	"os"
	"os/signal"
	"sync"

	"github.com/bugsnag/bugsnag-go"
)

func main() {
	bugsnag.Configure(bugsnag.Configuration{
		APIKey:          "dummy",
		ReleaseStage:    "development",
		ProjectPackages: []string{"main", "github.com/takkyuuplayer/bugsnag"},
	})

	killSignal := make(chan os.Signal, 1)
	signal.Notify(killSignal, os.Interrupt)

	var wg sync.WaitGroup
	wg.Add(1)

	go func() {
		defer wg.Done()
		log.Println("Worker started")
		<-killSignal
		log.Println("Worker shutting down")
	}()

	wg.Wait()
	log.Println("Worker shut down")
}
```

### What have been investigated

Fact: 

* If I replace `log.Println` with `fmt.Pringln`, it doesn't show the messages [NG]
* If I comment out bugsnag.Configure lines, it doesn't show the messages. [NG]
* go build main.go and then ./main also won't show the messages. [NG]
* on debugger mode (Goland using delve), it shows the message. [As Expected]

My GUESS: 

* It might be a race condition to write to STDERR. Reason: [log package](https://github.com/golang/go/blob/master/src/log/log.go#L76) and [panicwrap/monitor](https://github.com/bugsnag/panicwrap/blob/master/monitor.go#L13-L29) both uses os.Stderr. When I replace log with fmt, which is using Stdout, the messages are output.
* It might be [os.Exit(0)](https://github.com/bugsnag/panicwrap/blob/master/monitor.go#L28) is called too early. Reason: When I use debugger whose `Wrapped(c) = false`, it displays the message.

**Comment by takkyuuplayer** [comment] 2021-01-13 15:57
The guess seems wrong.  Eventually, when I move the signal handling block up like below snippet, it shows the messages (Some of them are twice, which is unexpected). It seems the wrapped code won't execute the lines after bugsnag.Configure properly.

```
$ go run main.go
2021/01/14 00:53:23 Worker started
2021/01/14 00:53:23 Worker started
^C2021/01/14 00:53:24 Worker shutting down
2021/01/14 00:53:24 Worker shutting down
2021/01/14 00:53:24 Worker shut down
```

```
package main

import (
	"github.com/bugsnag/bugsnag-go"
	"log"
	"os"
	"os/signal"
	"sync"
)

func main() {
	killSignal := make(chan os.Signal, 1)
	signal.Notify(killSignal, os.Interrupt)

	var wg sync.WaitGroup
	wg.Add(1)

	go func() {
		defer wg.Done()
		log.Println("Worker started")
		<-killSignal
		log.Println("Worker shutting down")
	}()

	bugsnag.Configure(bugsnag.Configuration{
		APIKey:          "dummy",
		ReleaseStage:    "development",
		ProjectPackages: []string{"main", "github.com/takkyuuplayer/bugsnag"},
	})

	wg.Wait()
	log.Println("Worker shut down")
}
```

**Comment by mattdyoung** [comment] 2021-02-01 15:54
Hi @takkyuuplayer 

We'll take a look when priorities allow and see if we can improve the behavior.

FYI - the repeated messages are because calling `Configure` forks the process:
https://docs.bugsnag.com/platforms/go/other/configuration-options/#panichandler

**Comment by tomlongridge** [comment] 2023-11-17 16:38
Closing this issue out as we don't believe there's a way to satisfactorily fix this with `panicwrap`. Our recommendation is to use the newer [bugsnag/panic-monitor](https://github.com/bugsnag/panic-monitor) library as documented here: https://docs.bugsnag.com/platforms/go/other/#reporting-unhandled-panics

**Closed by tomlongridge** 2023-11-17 16:38 UTC
Labels: bug, backlog
